sudo: required
language: generic
services:
 - docker

before_install:
  - docker build -t spencercarlson/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true spencercarlson/docker-react npm run test